import type { PresentationConstraint } from '@/types/presentation'

/** Seed graph rows — aptitude profile + cognitive fit routing */
export const DEFAULT_PRESENTATION_CONSTRAINTS: Omit<
  PresentationConstraint,
  'id' | 'user_id'
>[] = [
  {
    trait_key: 'low_analytical_reasoning',
    trait_label: 'Low analytical reasoning',
    relation: 'requires_format',
    target: 'pre_structured_components',
    target_label: 'Pre-structured tables, matrices, or node trees — not prose',
    provenance: { source: 'aptitude_profile', field: 'analytical_reasoning', percentile: 13 },
    enabled: true,
    sort_order: 1,
  },
  {
    trait_key: 'low_analytical_reasoning',
    trait_label: 'Low analytical reasoning',
    relation: 'forbids_element',
    target: 'sequential_essay',
    target_label: 'Sequential prose essays',
    provenance: { source: 'aptitude_profile', field: 'analytical_reasoning', percentile: 13 },
    enabled: true,
    sort_order: 2,
  },
  {
    trait_key: 'high_graphoria',
    trait_label: 'High graphoria',
    relation: 'requires_format',
    target: 'dense_tables_matrices',
    target_label: 'High-density tables and matrices for scanning',
    provenance: { source: 'aptitude_profile', field: 'graphoria', percentile: 70 },
    enabled: true,
    sort_order: 3,
  },
  {
    trait_key: 'high_graphoria',
    trait_label: 'High graphoria',
    relation: 'forbids_element',
    target: 'narrative_fluff',
    target_label: 'Introductory narrative fluff before data',
    provenance: { source: 'aptitude_profile', field: 'graphoria', percentile: 70 },
    enabled: true,
    sort_order: 4,
  },
  {
    trait_key: 'high_number_facility',
    trait_label: 'High number facility',
    relation: 'requires_format',
    target: 'metrics_in_grids',
    target_label: 'Numbers isolated in table/matrix cells — not inline prose',
    provenance: { source: 'aptitude_profile', field: 'number_facility', percentile: 85 },
    enabled: true,
    sort_order: 5,
  },
  {
    trait_key: 'low_number_memory',
    trait_label: 'Low number memory',
    relation: 'forbids_element',
    target: 'numbers_in_prose',
    target_label: 'Critical metrics buried inside sentence chains',
    provenance: { source: 'aptitude_profile', field: 'number_memory', percentile: 5 },
    enabled: true,
    sort_order: 6,
  },
  {
    trait_key: 'low_structural_visualization',
    trait_label: 'Low structural visualization',
    relation: 'requires_format',
    target: 'hierarchical_node_trees',
    target_label: 'Hierarchical node trees for systems and flow',
    provenance: { source: 'aptitude_profile', field: 'structural_visualization', percentile: 5 },
    enabled: true,
    sort_order: 7,
  },
  {
    trait_key: 'low_structural_visualization',
    trait_label: 'Low structural visualization',
    relation: 'forbids_element',
    target: 'spatial_charts',
    target_label: 'Unanchored spatial charts or coordinate-heavy maps',
    provenance: { source: 'aptitude_profile', field: 'structural_visualization', percentile: 5 },
    enabled: true,
    sort_order: 8,
  },
  {
    trait_key: 'low_vocabulary_retention',
    trait_label: 'Low vocabulary retention',
    relation: 'forbids_element',
    target: 'ornate_jargon',
    target_label: 'Ornate jargon or academic filler',
    provenance: { source: 'aptitude_profile', field: 'vocabulary', percentile: 20 },
    enabled: true,
    sort_order: 9,
  },
  {
    trait_key: 'objective_personality',
    trait_label: 'Objective personality',
    relation: 'requires_format',
    target: 'big_picture_lead',
    target_label: 'One-line punchline lead before structure',
    provenance: { source: 'aptitude_profile', field: 'objective_personality' },
    enabled: true,
    sort_order: 10,
  },
  {
    trait_key: 'format_routing',
    trait_label: 'Cognitive fit routing',
    relation: 'requires_format',
    target: 'intent_matched_component',
    target_label: 'Match table / matrix / tree to query intent',
    provenance: { source: 'cognitive_fit_theory', refs: ['Vessey 1991', 'Samuel 2022'] },
    enabled: true,
    sort_order: 11,
  },
  {
    trait_key: 'format_routing',
    trait_label: 'Cognitive fit routing',
    relation: 'forbids_element',
    target: 'ascii_markdown_tables',
    target_label: 'Raw ASCII or markdown tables (|---|)',
    provenance: { source: 'presentation_interceptor' },
    enabled: true,
    sort_order: 12,
  },
]
